bwsw/cloudstack-ui

- src/app/template/template/template.component.scss
- src/app/template/template/template.component.ts
- src/app/vm/vm-filter/vm-filter.component.html
- src/app/vm/vm-filter/vm-filter.component.scss
- src/public/i18n/en.json
- src/public/i18n/ru.json
> #112, #117, #118, #119 layout fixes

- src/app/app.component.ts
- src/app/shared/services/auth.service.spec.ts
- src/app/shared/services/auth.service.ts
- src/app/shared/services/user.service.ts
Inactivity timeout fixed for user that does not refresh the page after logging in
> (closes #228): Inactivity timeout fix

- src/app/vm/vm-creation/data/vm-creation-data.ts
- src/app/vm/vm-creation/data/vm-creation-state.ts
- src/app/vm/vm-creation/vm-creation.component.scss
- src/app/vm/vm-creation/vm-creation.component.ts
- src/app/vm/vm-creation/vm-creation.service.ts
- src/app/vm/vm-sidebar/vm-detail.component.html
> (closes #242) Add "No SSH key" option to SSH key selector

- CONTRIBUTING.md
- package.json
Add CONTRIBUTING.md to help developers follow the same rules
> docs(contributing): Add CONTRIBUTING.md file

- src/app/security-group/sg-creation/sg-creation-rule.component.html
- src/app/security-group/sg-creation/sg-creation-rule.component.spec.ts
- src/app/security-group/sg-creation/sg-creation.component.html
- src/app/security-group/sg-creation/sg-creation.component.scss
- src/app/shared/components/notification-box/notification-box-item.component.html
- src/app/shared/components/notification-box/notification-box.component.html
- src/app/shared/components/notification-box/notification-box.component.scss
- src/app/shared/shared.module.ts
- src/app/ssh-keys/ssh-key-list.component.html
- src/app/template/template-list/template-list.component.html
- src/app/template/template-list/template-list.component.scss
get rid of MDL component, replace it by MD's one
> (closes #281) Replace lists by MD component

- src/app/template/template-sidebar/base-template-sidebar.component.html
- src/app/template/template-sidebar/base-template-sidebar.component.scss
- src/app/template/template-sidebar/base-template-sidebar.component.ts
- src/app/template/template-sidebar/iso-sidebar.component.ts
- src/app/template/template-sidebar/template-sidebar.component.ts
- src/app/template/template.module.ts
replace template src URL view by copy icon
> (closes #303) Change template src URL view

- src/app/shared/services/notification.service.spec.ts
- src/app/shared/services/notification.service.ts
- src/app/shared/shared.module.ts
Get rid of mdl-snack-bar-service, replace it by md-snack-bar component
> (closes #277) Replace snackbar with material2 snackbar

- src/app/template/iso-attachment/iso-attachment.component.html
- src/app/template/iso-attachment/iso-attachment.component.ts
- src/app/template/template-filter-list/template-filter-list-selector.component.html
- src/app/template/template-filter-list/template-filter-list-selector.component.ts
- src/app/template/template-filter-list/template-filter-list.component.html
- src/app/template/template.module.ts
- src/app/vm/vm-creation/template/vm-template-dialog.component.html
fix iso attachment list and reformat code of filtered template lists
> (closes #302) Fix ISO attachment list

- src/app/shared/services/cache.service.ts
fix error in vm list loading: invalidate cache
> (closes #307) Fix error in VM list loading

- src/app/template/template-filter-list/template-filter-list.component.ts
- src/app/template/template-page/template-page.component.ts
reload the template list bug after creating/deleting template/ISO
> (closes #324) Reload the template list bug

- src/app/shared/services/async-job.service.ts
fix redirect to login page error, if the action with vm was started, the user was logged out, the login page does not load, the error in console occur
> (closes #319) Problem with logout

- src/app/template/template/template.component.ts
> fix(template): add condition for template handleClick

- src/app/auth/login.component.ts
> fix(login): add condition for queryParams

- .build/nginx.conf
- .build/startup.sh
- proxy.conf.js
- src/app/vm/vm-actions/vm-webshell.ts
- src/app/vm/web-shell/web-shell.service.ts
- src/config/config.json
Webshell endpoint removed from config. Docker WEBSHELL_PLUGIN_ENDPOINT env parameter added
> fix(webshell): Webshell config changed. Endpoint removed.

- src/app/events/event-list.component.spec.ts
- src/app/events/event-list.component.ts
- src/app/shared/services/language.service.ts
fix the view of weeks in the calendar
> (closes #400) Fix the view of weeks in the calendar

- src/app/ssh-keys/ssh-key-list-item.component.scss
> (closes #430) Fix layout problem on the SSHkeys page

- src/app/security-group/sg-template-list/sg-template-list-item.component.html
fix popover bug on the security groups page
> (closes #432) Fix popover bug on the security groups page

- src/app/service-offering/service-offering-dialog/service-offering-dialog.component.ts
fix service offering dialog bug
> (closes #439) Fix service offering bug

- src/app/shared/components/vm-statistics/vm-statistics.component.html
- src/app/shared/components/vm-statistics/vm-statistics.component.scss
- src/app/snapshot/recurring-snapshots/recurring-snapshots.component.html
- src/app/template/template-filters/template-filters.component.html
- src/app/template/template-sidebar/base-template-sidebar.component.html
- src/app/vm/vm-sidebar/vm-sidebar.component.html
#418 - add selectedIndex attribute
#415 - remove arrows
> fix(tab-switch): fix tab index

- src/app/security-group/sg-template-creation/sg-template-creation-dialog.component.ts
- src/app/ssh-keys/ssh-key-creation/ssh-key-creation.component.ts
fix redirection links when creation og entity was cancelled
> (closes #450) Fix redirection links for creation modals

- src/app/tags/tags-view/tags-view.component.html
- src/app/tags/tags-view/tags-view.component.scss
- src/app/tags/tags-view/tags-view.component.ts
- src/app/template/template-tags/template-tags.component.html
> fix(add-tag): add condition for add button

- src/app/events/event-list.component.html
- src/app/events/event-list.component.scss
- src/app/events/event-list.component.spec.ts
- src/app/events/event-list.component.ts
- src/app/security-group/sg-rules/sg-rule.component.html
- src/app/security-group/sg-rules/sg-rule.component.ts
- src/app/security-group/sg-rules/sg-rules.component.html
- src/app/security-group/sg-rules/sg-rules.component.scss
- src/app/shared/components/table/table.component.html
- src/app/shared/components/table/table.component.ts
- src/app/shared/components/table/table.ts
- src/app/shared/shared.module.ts
- src/app/snapshot/recurring-snapshots/policy-list/policy-list.component.html
- src/app/snapshot/recurring-snapshots/policy-list/policy-list.component.scss
- src/app/snapshot/recurring-snapshots/policy-list/policy-list.component.ts
- src/app/vm/vm-sidebar/storage-detail/volume/snapshot/snapshot-modal.component.html
- src/app/vm/vm-sidebar/storage-detail/volume/snapshot/snapshot-modal.component.ts
- src/style/app.scss
replace mdl-data-table components by md-table
> (closes #329) Replace mdl tables by md-table

- src/index.html
add alert for user if his browser version is older
> (closes #26) Add alert for users if their browser is out of date

- src/app/vm/vm-actions/vm-reset-password.ts
> (feat): update canActivate for action 'reset password'

- .build/nginx.conf
- .build/run.sh
- .build/startup.sh
- README.md
CLIENT_ENDPOINT parameter introduced instead
> fix(docker): API and Console endpoints removed (#427)

- src/app/vm/vm-creation/components/security-group/vm-creation-security-group.component.scss
- src/i18n/en.json
- src/i18n/ru.json
#549 
add new translation for sg-groups, update tab width
> fix(tab-arrows): add new translation for sg-groups, update tab width

- src/app/shared/models/hypervisor.model.ts
- src/app/shared/models/index.ts
- src/app/shared/services/hypervisor.service.ts
- src/app/shared/shared.module.ts
- src/app/template/template-creation/template-creation.component.html
- src/app/template/template-creation/template-creation.component.scss
- src/app/template/template-creation/template-creation.component.ts
- src/i18n/en.json
- src/i18n/ru.json
> feat(optional): add template optional fields

- src/app/shared/services/utils/utils.service.spec.ts
- src/app/shared/services/utils/utils.service.ts
- src/app/vm/vm-list/vm-list-item.component.scss
- src/app/vm/vm-list/vm-list-item.component.ts
fix font color that is based on background color
> (closes #548) VM colors should have different text color

- src/app/pulse/charts/aggregation-selector.component.html
- src/app/pulse/charts/aggregation-selector.component.ts
- src/app/pulse/charts/pulse-disk-chart/pulse-disk-chart.component.scss
- src/app/pulse/charts/pulse-disk-chart/pulse-disk-chart.component.ts
- src/app/pulse/charts/pulse-network-chart/pulse-network-chart.component.scss
- src/app/pulse/charts/pulse-network-chart/pulse-network-chart.component.ts
- src/app/pulse/vm-pulse/vm-pulse.component.html
fix the styles of entity selectors, move it to the one row with aggregation selectors
> (closes #576) Disk and NIC selector are not properly positioned on Pulse Modal

- src/app/template/template-sidebar/template-os-icon/template-os-icon.component.html
- src/app/template/template-sidebar/template-os-icon/template-os-icon.component.scss
fix size of icons in images lists
> fix(templates) fix size of icons in the images list

- src/app/vm/vm-creation/template/vm-creation-template.component.html
- src/app/vm/vm-creation/template/vm-creation-template.component.scss
- src/app/vm/vm-creation/template/vm-template-dialog.component.html
- src/app/vm/vm-creation/vm-creation.component.html
- src/app/vm/vm-creation/vm-creation.component.scss
fix 'select' button view on vm creation dialog
> (closes #587) Fix 'select' button view on vm creation dialog

- src/app/account/account-container/account.container.ts
- src/app/domains/redux/domains.actions.ts
- src/app/domains/redux/domains.effects.ts
- src/app/domains/redux/domains.reducers.ts
- src/app/shared/components/grouped-card-list/grouped-card-list.component.ts
- src/app/shared/components/sidebar/sidebar.component.ts
- src/app/shared/services/ssh-keypair.service.ts
- src/app/ssh-keys/containers/ssh-key-list.container.html
- src/app/ssh-keys/containers/ssh-key-list.container.ts
- src/app/ssh-keys/redux/ssh-key.actions.ts
- src/app/ssh-keys/redux/ssh-key.effects.ts
- src/app/ssh-keys/redux/ssh-key.reducers.ts
- src/app/ssh-keys/ssh-key-creation/containers/ssh-key-creation-dialog.container.ts
- src/app/ssh-keys/ssh-key-creation/ssh-key-creation-dialog.component.html
- src/app/ssh-keys/ssh-key-creation/ssh-key-creation-dialog.component.ts
- src/app/ssh-keys/ssh-key-creation/ssh-key-creation.component.ts
- src/app/ssh-keys/ssh-key-filter/ssh-key-filter.component.html
- src/app/ssh-keys/ssh-key-filter/ssh-key-filter.component.ts
- src/app/ssh-keys/ssh-key-list/ssh-key-list.component.html
- src/app/ssh-keys/ssh-key-list/ssh-key-list.component.ts
- src/app/ssh-keys/ssh-keys-page/ssh-keys-page.component.html
- src/app/ssh-keys/ssh-keys-page/ssh-keys-page.component.ts
- src/app/ssh-keys/ssh-keys.module.ts
- src/app/ssh-keys/ssh-keys.routing.ts
Load the list of SSH keys using ngrx, create and remove SSH keys using ngrx
> (closes #599) Use ngrx for ssh keys

- src/app/security-group/sg-filter/sg-filter.component.ts
- src/app/template/template-sidebar/base-template-sidebar.component.scss
- src/app/vm/vm-creation/vm-creation.component.scss
This pull request also includes #619 task
> (closes#618) Minor interface bugs on laptop

- src/app/account/account-sidebar/account-details/account-details.component.html
- src/app/account/account-sidebar/account-limits/account-limits.component.html
- src/app/account/account-sidebar/account-limits/account-limits.component.ts
- src/app/account/account-sidebar/account-settings/account-configuration/account-configuration.component.html
- src/app/account/account-sidebar/account-sidebar.component.html
- src/app/account/account-sidebar/account-sidebar.component.ts
- src/app/account/account-sidebar/account-statistic/account-statistics.component.html
- src/app/shared/components/parameters-pair/parameters-edit-pair.component.html
- src/app/shared/components/parameters-pair/parameters-edit-pair.component.ts
- src/app/shared/components/parameters-pair/parameters-pair.component.html
- src/app/shared/components/parameters-pair/parameters-pair.component.scss
- src/app/shared/components/parameters-pair/parameters-pair.component.ts
- src/app/shared/shared.module.ts
fix style, add component for parameters key-value pairs
> fix(account-params): fix account parameters view

- src/app/auth/login.component.ts
> feat(login-form) - add key to local storage to save login form view mode

- src/app/shared/actions/template-actions/delete/base-template-delete.ts
- src/app/shared/actions/template-actions/delete/template-delete.ts
- src/app/snapshot/snapshot-actions.service.ts
- src/app/template/redux/template.effects.ts
- src/app/template/shared/base-template.service.ts
- src/app/template/template-creation/containers/template-creation.container.ts
- src/app/template/template-creation/template-creation.component.html
- src/app/template/template-creation/template-creation.component.ts
+ fix templates deleting effect
> fix(template) fix template creation from VM snapshot (closes #698)

- src/app/volume/container/volume-creation.container.ts
- src/app/volume/volume-creation/volume-creation-dialog.component.ts
> fix(limit-size) - get minDiskSize from user capabilities

- src/app/security-group/sg-filter/sg-filter.component.html
- src/app/shared/components/grouped-list/grouped-list.component.ts
- src/app/shared/models/grouping.model.ts
- src/app/ssh-keys/containers/ssh-key-filter/ssh-key-filter.container.html
- src/app/ssh-keys/containers/ssh-key-filter/ssh-key-filter.container.ts
- src/app/ssh-keys/containers/ssh-key-page/ssh-key-page.container.ts
- src/app/ssh-keys/redux/ssh-key.actions.ts
- src/app/ssh-keys/redux/ssh-key.reducers.ts
- src/app/ssh-keys/ssh-key-creation/ssh-key-creation.component.ts
- src/app/ssh-keys/ssh-key-filter/ssh-key-filter.component.html
- src/app/ssh-keys/ssh-key-filter/ssh-key-filter.component.ts
- src/app/ssh-keys/ssh-key-list/ssh-key-list.component.ts
- src/app/ssh-keys/ssh-keys-page/ssh-keys-page.component.ts
- src/app/vm/vm-filter/vm-filter.component.html
> fix(account-filter): Account filter added to Firewall section

- src/app/snapshot/recurring-snapshots/policy-editor/monthly/monthly-policy.component.ts
- src/app/snapshot/recurring-snapshots/time-picker/time-picker.component.ts
> fix(snapshot-schedule): fix time set conditions

- src/app/reducers/security-groups/redux/sg.reducers.ts
- src/app/security-group/sg-list/security-group-list.component.html
> fix(sg-filter): Fix filter by account

- src/app/shared/models/volume.model.ts
- src/app/vm/vm-sidebar/storage-detail/volumes/snapshot/snapshot-modal.component.ts
- src/app/vm/vm-sidebar/storage-detail/volumes/snapshot/snapshot-modal.container.ts
- src/app/vm/vm-sidebar/storage-detail/volumes/snapshot/snapshots.component.ts
> fix(snapshot-modal): Fix snapshot modal window bugs

- src/app/vm/vm-sidebar/network-detail/nics/nic/nic-fields/nic-fields.component.html
- src/app/vm/vm-sidebar/network-detail/nics/nic/nic.component.html
> feat(ipv6):  Add ipV6 fields to vm-network details view

- src/app/shared/components/top-bar/top-bar.component.ts
- src/app/template/template-creation/template-creation.component.html
> fix(notification-box): fix notification moves

- src/app/account/creation-form/account-creation-dialog.component.html
- src/app/account/creation-form/account-creation-dialog.component.ts
- src/app/reducers/accounts/redux/accounts.effects.ts
- src/app/shared/models/account.model.ts
> fix(account-creation): Remove "account" field

- src/app/shared/actions/volume-actions/volume-resize/volume-resize.component.html
- src/app/shared/actions/volume-actions/volume-resize/volume-resize.component.spec.ts
- src/app/shared/actions/volume-actions/volume-resize/volume-resize.component.ts
> fix(resize-disk): Show resize slider for customized diskOffering

- src/app/reducers/security-groups/redux/sg.reducers.ts
- src/app/reducers/vm/redux/vm-creation.effects.ts
- src/app/shared/components/security-group-builder/security-group-builder.component.ts
+ fix selection on builder 
**To test:**
- vm_creation_firewall_template
- vm_creation_firewall_shared
**Regression:** vm_firewall_display
Test on `qqcky/921-vm-creation-shared-sg-bug`.
> fix(security-groups): show only shared in vm creation (closes #921)

- package.json
I add script for generating checkstyle file form lint.
It can be used with CI to generate statistics.
> build(lint): add script for generating checkstyle file

- src/app/account/account-sidebar/account-sidebar.component.ts
- src/app/account/account/account-item.component.ts
- src/app/shared/models/index.ts
- src/app/shared/utils/account.ts
This is a fix for the [previous PR](https://github.com/bwsw/cloudstack-ui/pull/1043) that was merged by mistake
> fix(account): fix the ability to delete the current account from sidebar

- package.json
- src/index.html
- src/main.ts
- yarn.lock
Hammerjs dependency was moved from index.html to packages.json
> refactor: move hammerjs to package.json

- src/app/security-group/sg-filter/containers/sg-filter.container.ts
- src/app/shared/components/vm-statistics/vm-statistic.container.ts
- src/app/shared/components/vm-statistics/vm-statistics.component.ts
> fix(security-group): update filter configuration

- src/app/vm/vm-sidebar/storage-detail/volumes/snapshot/snapshot-modal.component.html
> fix: add tooltips in snapshot dialog

- src/app/template/template/card-item/template-card-item.component.html
- src/app/template/template/card-item/template-card-item.component.scss
- src/app/template/template/card-item/template-card-item.component.ts
Fixes #1070 
Also, updated CSS to show pointer cursor only on a card and not between them
> fix(image): remove tooltips of the card fields

- src/app/reducers/volumes/redux/volumes.reducers.ts
- src/app/volume/volume-item/card-item/volume-card-item.component.html
- src/app/volume/volume-item/card-item/volume-card-item.component.scss
- src/app/volume/volume-item/card-item/volume-card-item.component.ts
- src/app/volume/volume-item/volume-item.component.ts
> bug(storage): delete the description field from the card and search

- src/app/security-group/containers/sg-rules.container.ts
- src/app/security-group/sg-rules/sg-rules.component.spec.ts
- src/app/security-group/sg-rules/sg-rules.component.ts
Fixes #1016 
But there is another redirect performs after navigating and it takes some time. An issue for this will be created and fixed.
> fix: add query parameter for redirect to shared SG

- src/app/shared/components/create-update-delete-dialog/create-update-delete-dialog.component.html
- src/app/vm/vm-creation/vm-creation.component.html
> fix: validation of affinity group name

- src/app/shared/components/parameters-pair/parameters-pair.component.scss
Fixes #987 
Used code from #1076 that relate to issue
> fix: fix layout for sidebar key-value data

- src/app/reducers/security-groups/redux/sg.reducers.ts
- src/app/security-group/sg-page/security-group-page.component.html
> fix(firewall): orphan filter work only in private sg mode

- src/app/security-group/sg-list-item/security-group-list-item.component.ts
> fix(firewall): check if vm exists with a name for private sg

- src/app/snapshot/snapshots-page/snapshot-list-item/snapshot-actions/snapshot-action.component.ts
- src/app/snapshot/snapshots-page/snapshot-list-item/snapshot-actions/snapshot-action.service.ts
- src/app/vm/vm-sidebar/storage-detail/volumes/snapshot/snapshot-modal.component.html
- src/app/vm/vm-sidebar/storage-detail/volumes/snapshot/snapshot-modal.component.ts
- src/app/vm/vm-sidebar/storage-detail/volumes/snapshot/snapshots.component.html
- src/app/vm/vm-sidebar/storage-detail/volumes/snapshot/snapshots.component.ts
> fix(snapshots): disable snapshot actions based on states

- src/app/shared/pipes/highlight.pipe.ts
> fix: add check for the highlight pipe that text exist

- src/app/shared/services/affinity-group.service.ts
- src/app/vm/container/vm-detail.container.ts
- src/app/vm/vm-sidebar/vm-detail/affinity-group/affinity-group.component.ts
> fix(vm): update handling an affinity group creation response

- src/app/tags/tags-view/tags-view.component.ts
- src/app/tags/tags.component.ts
> fix(tags): use validation by key based on existing tags when creating and updating

- src/app/shared/services/account.service.ts
> fix(accounts): update response handler for disabling account

- src/app/security-group/sg-filter/containers/sg-filter.container.ts
> fix(sg): use session storage instead local storage for sg filters

- src/app/security-group/components/sg-rule-addition-form/sg-rule-addition-form.component.html
- src/style/app.scss
> fix(sg): update the width of the autocompletion window for icmp codes and types

- src/app/account/account-container/account-details.container.ts
- src/app/account/account-sidebar/account-limits/account-limits.component.html
- src/app/account/account-sidebar/account-limits/account-limits.component.ts
- src/app/account/account-sidebar/account-statistic/account-statistics.component.ts
- src/app/reducers/resource-limit/redux/resource-limits.actions.ts
- src/app/reducers/resource-limit/redux/resource-limits.effects.ts
- src/app/reducers/resource-limit/redux/resource-limits.reducers.ts
- src/app/shared/models/resource-limit.model.ts
- src/app/shared/services/resource-limit.service.ts
> fix(accounts): fix update of the accounts limits

- src/app/reducers/security-groups/redux/sg.effects.ts
- src/app/reducers/templates/redux/template.effects.ts
- src/app/security-group/containers/security-group-creation.container.ts
- src/app/security-group/sg-creation/security-group-creation-dialog.component.ts
- src/app/security-group/sg-creation/security-group-creation.component.html
- src/app/security-group/sg-creation/security-group-creation.component.ts
- src/app/template/template-creation/containers/template-creation.container.ts
> fix(sg): do not redirect to the new SG after its creation

- src/app/security-group/sg-list-item/row-item/security-group-row-item.component.html
> fix(firewall): use proper SG interface field names

- src/app/shared/components/notification-box/notification-box-item.component.ts
- src/app/shared/components/notification-box/notification-box.component.html
- src/app/shared/components/notification-box/notification-box.component.ts
- src/app/shared/services/jobs-notification.service.spec.ts
- src/app/shared/services/jobs-notification.service.ts
- src/polyfills.ts
> fix: use BehaviorSubject instead of Subject in job notification

- src/app/reducers/vm/redux/vm-creation.effects.ts
- src/app/reducers/vm/redux/vm.actions.ts
- src/app/reducers/vm/redux/vm.effects.ts
- src/app/reducers/vm/redux/vm.reducers.spec.ts
- src/app/reducers/vm/redux/vm.reducers.ts
- src/app/tags/tags-view/tags-view.component.ts
- src/app/vm/shared/vm.model.ts
- src/testutils/data/vitrual-machines.ts
> fix(vm): reload vm after creation

- src/app/core/config/default-configuration.ts
- src/app/dialog/dialog-service/ask-dialog/ask-dialog.component.scss
- src/app/reducers/vm/redux/vm.reducers.ts
- src/app/reducers/volumes/redux/volumes.reducers.ts
- src/app/shared/actions/volume-actions/volume-actions.container.ts
- src/app/vm/vm-page/vm-page.component.ts
- src/app/volume/volume-page/volume-page.component.ts
> fix: show vm and volume suggestion dialogs based on tags

- src/app/vm/vm-creation/containers/vm-creation.container.ts
> fix(vm): make all loading selectors equivalent

- src/app/root-store/idle-monitor/idle-monitor.effects.ts
> fix: subscribe to cold observable to make an actual request

- config-guide.md
- src/app/core/config/default-configuration.ts
- src/app/reducers/disk-offerings/redux/disk-offerings.actions.ts
- src/app/reducers/disk-offerings/redux/disk-offerings.effects.ts
- src/app/reducers/disk-offerings/redux/disk-offerings.reducers.ts
- src/app/shared/actions/volume-actions/volume-resize.container.ts
- src/app/shared/actions/volume-actions/volume-resize/volume-resize.component.html
- src/app/shared/actions/volume-actions/volume-resize/volume-resize.component.ts
- src/app/shared/components/disk-offering/disk-offering-dialog/disk-offering-dialog.component.html
- src/app/shared/components/disk-offering/disk-offering-dialog/disk-offering-dialog.component.scss
- src/app/shared/components/disk-offering/disk-offering-dialog/disk-offering-dialog.component.spec.ts
- src/app/shared/components/disk-offering/disk-offering-dialog/disk-offering-dialog.component.ts
- src/app/shared/components/disk-offering/disk-offering-selector/disk-offering-selector.component.ts
- src/app/shared/models/config/config.interface.ts
- src/app/shared/services/utils/utils.service.ts
- src/app/vm/vm-creation/containers/vm-creation.container.ts
- src/app/vm/vm-creation/vm-creation.component.html
- src/app/vm/vm-creation/vm-creation.component.ts
- src/app/vm/vm-sidebar/storage-detail/volumes/volume-details/volume-details.component.html
- src/app/volume/container/volume-creation.container.ts
- src/app/volume/container/volume-details.container.ts
- src/app/volume/volume-creation/volume-creation-dialog.component.html
- src/app/volume/volume-creation/volume-creation-dialog.component.ts
- src/app/volume/volume-sidebar/details/disk-offering/volume-sidebar-disk-offering.component.html
- src/app/volume/volume-sidebar/details/disk-offering/volume-sidebar-disk-offering.component.ts
- src/config/config-example.json
- src/i18n/en.json
- src/i18n/ru.json
> refactor: update a disk offering list view

- src/i18n/ru.json
> fix(vm creation): update russian translation

- src/app/vm/vm-sidebar/vm-sidebar.component.html
> fix(vm): update color picker binding

- src/app/shared/models/volume.model.ts
- src/app/vm/vm-sidebar/storage-detail/volumes/volume-details/volume-details.component.html
> fix(vm): fix volumes information in vm sidebar

- src/app/vm/vm-creation/api-log/vm-api-log.component.ts
> fix(vm-create): fix notification when copy api logs on create error (#1569)

- e2e/disk-creation.e2e-spec.ts
- e2e/pages/login.po.ts
- e2e/pages/vm-creation.po.ts
- e2e/protractor.conf.js
- e2e/vm-creation.e2e-spec.ts
Fix e2e tests for CI in headless mode.
> fix e2e tests for CI

- e2e/disk-details.e2e-spec.ts
- e2e/pages/disk-list.po.ts
- e2e/pages/disk-sidebar.po.ts
- protractor.conf.js
added disk details without tests of creation template and reverting disk to snapshot
> diskDetailsTest

- package.json
- src/app/events/components/event-list.component.html
- src/app/events/components/event-list.component.ts
- src/app/security-group/sg-filter/sg-filter.component.html
- src/app/security-group/sg-filter/sg-filter.component.ts
- src/app/shared/components/time-zone/time-zone.component.html
- src/app/shared/components/time-zone/time-zone.component.ts
- src/app/shared/shared.module.ts
- src/app/snapshot/snapshots-page/snapshot-filter/vm-snapshot-filter.component.html
- src/app/snapshot/snapshots-page/snapshot-filter/vm-snapshot-filter.component.ts
- src/app/snapshot/snapshots-page/snapshot-filter/volume-snapshot-filter.component.html
- src/app/snapshot/snapshots-page/snapshot-filter/volume-snapshot-filter.component.ts
- src/app/ssh-keys/ssh-key-filter/ssh-key-filter.component.html
- src/app/ssh-keys/ssh-key-filter/ssh-key-filter.component.ts
- src/app/template/template-filters/template-filters.component.html
- src/app/template/template-filters/template-filters.component.ts
- src/app/vm-logs/vm-logs-filter/vm-logs-filter.component.html
- src/app/vm-logs/vm-logs-filter/vm-logs-filter.component.ts
- src/app/vm/vm-filter/vm-filter.component.html
- src/app/vm/vm-filter/vm-filter.component.ts
- src/app/volume/volume-filter/volume-filter.component.html
- src/app/volume/volume-filter/volume-filter.component.ts
- src/i18n/en.json
- src/i18n/ru.json
- src/style/app.scss
for timezone
for account select
I am also doing the work for quota and usage support in quota-usage branch.
And a dashboard
> add search input to mat-select

- src/app/shared/components/sidebar/sidebar-container/sidebar-container.component.scss
Tested: Chromium & Opera & Firefox
> fix(sidebar): doesn't scroll (#1666)

- src/app/template/template-filter-list/template-filter-list-selector.component.html
> Bring back templates search in vm creation dialog

- src/app/auth/login.component.html
- src/app/auth/login.component.scss
- src/app/auth/login.component.spec.ts
- src/app/auth/login.component.ts
> Login form enchancements

- src/app/security-group/sg-filter/containers/sg-filter.container.ts
> Set SecurityGroupViewMode.Shared as the default view mode

- src/app/service-offering/service-offering-list/service-offering-list.component.html
- src/app/shared/components/disk-offering/disk-offering-dialog/disk-offering-dialog.component.html
- src/app/shared/components/disk-offering/disk-offering-dialog/disk-offering-dialog.component.spec.ts
- src/app/shared/components/disk-offering/disk-offering-dialog/disk-offering-dialog.component.ts
- src/app/shared/pipes/convert-to-mb.pipe.ts
- src/app/shared/services/utils/utils.service.ts
- src/app/shared/shared.module.ts
- src/app/vm/vm-sidebar/storage-detail/volumes/volume-details/volume-details.component.html
- src/app/vm/vm-sidebar/vm-detail/service-offering-details/service-offering-details.component.html
- src/app/volume/volume-sidebar/details/disk-offering/volume-sidebar-disk-offering.component.html
- src/app/volume/volume-sidebar/details/disk-offering/volume-sidebar-disk-offering.component.ts
> Divide MBs by 10^6 and round the result

- src/app/vm/vm-creation/vm-creation.component.html
- src/app/vm/vm-creation/vm-creation.component.ts
> Compare zones by id in mat-select in VM creation

- src/app/reducers/vm/redux/vm-creation.effects.ts
> Can't create VMs if security groups feature is disabled

- package.json
- src/app/auth/login.component.spec.ts
- src/app/auth/login.component.ts
- src/app/reducers/affinity-groups/redux/affinity-groups.effects.spec.ts
- src/app/reducers/disk-offerings/redux/disk-offerings.effects.spec.ts
- src/app/reducers/service-offerings/redux/service-offerings.reducers.spec.ts
- src/app/root-store/config/config.selectors.ts
- src/app/root-store/server-data/user-tags/user-tags.effects.spec.ts
- src/app/shared/components/security-group-builder/security-group-builder.component.spec.ts
- src/app/shared/components/security-group-builder/security-group-builder.component.ts
- src/app/shared/services/service-offering.service.spec.ts
- src/app/vm-logs/redux/vm-logs.reducers.spec.ts
- src/app/vm/selectors/service-offering.selectors.spec.ts
- src/app/vm/vm-sidebar/vm-detail/os-type/os-type.component.spec.ts
- src/app/vm/vm-sidebar/vm-detail/vm-user-data-dialog/vm-user-data-dialog.component.spec.ts
- yarn.lock
> Use ngrx mock store

- src/app/pulse/pulse.module.ts
- src/app/pulse/vm-pulse/pulse-params-persistence.spec.ts
- src/app/pulse/vm-pulse/pulse-params-persistence.ts
- src/app/pulse/vm-pulse/pulse-params.ts
- src/app/pulse/vm-pulse/vm-pulse.component.spec.ts
- src/app/pulse/vm-pulse/vm-pulse.component.ts
> Store pulse filter values by user id
